version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/dockerfiles/Dockerfile
    environment:
     - MONGOHOST=mongodb
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://${MONGOUSER:-root}:${MONGOPASSWORD:-password}@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
